Vineflower/vineflower

build.gradle
src/org/jetbrains/java/decompiler/modules/decompiler/exps/ConstExprent.java

This PR uninlines commonly used values, such as mutations of pi and e. This greatly improves code readability in the decompiled output.

Uninline double and float values

---

src/org/jetbrains/java/decompiler/modules/decompiler/exps/FunctionExprent.java
src/org/jetbrains/java/decompiler/util/IntHelper.java

This PR improves two pain points with FernFlower's bitwise operation code, specifically:
* `& 65535` and `& 0xFFFF` being decompiled as `& '\uffff'`
* Hex values used in color bit masking such as `0xFF0000`, `0xFF00`, and `0xFF` not being decompiled properly
These issues have been addressed with this PR.

Improve output of bitwise operations

---

src/org/jetbrains/java/decompiler/modules/decompiler/exps/AssignmentExprent.java

This PR fixes a longstanding issue where fernflower would assign boolean values to integer values. It also fixes it in the worst way possible. Sometimes, fernflower would produce a result of `int i = true;` for any nonzero values of i, causing much confusion for new modders. Fixing this will improve the experience of new modders looking at minecraft's code.

Fix boolean values assigned to int variables

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java
testData/results/TestClassLambda.dec
testData/results/TestLambdaParams.dec

Removes the parentheses from lambdas with only 1 parameter, making them cleaner. Thank you so much for this @williambl!

Remove parentheses from single-param lambdas

---

src/org/jetbrains/java/decompiler/modules/decompiler/exps/ConstExprent.java

Oversight of #7 
Done in the GH web interface but I don't see anything that could go wrong

Re-add uninlining for negative double/float consts

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java
src/org/jetbrains/java/decompiler/main/rels/ClassWrapper.java
src/org/jetbrains/java/decompiler/struct/StructClass.java
src/org/jetbrains/java/decompiler/struct/StructMethod.java
src/org/jetbrains/java/decompiler/struct/attr/StructCodeAttribute.java
src/org/jetbrains/java/decompiler/struct/consts/ConstantPool.java
src/org/jetbrains/java/decompiler/struct/lazy/LazyLoader.java

Instead of discarding the bytecode and exception handler data this saves it in the `StructCodeAttribute` so it doesn't have to get parsed from the class again.
This prevents a crash where the wrong bytecode is used in case of duplicate methods.
Might also have some performance improvements by not having to parse the whole class again just to get the bytecode.
Both versions of the method will show up in the output and a warning is logged.

Improved handling of multiple methods using the same name and descriptor

---

src/org/jetbrains/java/decompiler/util/VBStyleCollection.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/TestNestedLoops.dec

This caused a NullPointerException during decompilation of TestNestedLoops, which is now decompiled semi-reasonably

Fix VBStyleCollection::removeWithKey for elements that are not present

---

src/org/jetbrains/java/decompiler/main/ClassesProcessor.java
src/org/jetbrains/java/decompiler/main/collectors/ImportCollector.java
src/org/jetbrains/java/decompiler/modules/renamer/IdentifierConverter.java
src/org/jetbrains/java/decompiler/struct/StructContext.java
src/org/jetbrains/java/decompiler/struct/StructMember.java
src/org/jetbrains/java/decompiler/struct/StructMethod.java
src/org/jetbrains/java/decompiler/struct/lazy/LazyLoader.java
test/org/jetbrains/java/decompiler/SingleClassesEntireClasspathTest.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java

Here are some performance improvements, mainly focused on making tests run faster, but these are also generally useful.
- Run tests requiring the "include entire classpath" option separately
- That option adds ~500ms of setup time to each test, only use it where it affects the output
- Lazy load all library classes
- This also makes the decompiles using "include entire classpath" faster
- Only read Code attributes of own methods
- Parsing the Code attribute of libraries is not necessary, so some time can be saved by skipping it

Some performance improvements

---

src/org/jetbrains/java/decompiler/main/decompiler/SingleFileSaver.java

ZipOutputStream is not concurrent, so it is clear that this would create
such issues. Of course this fix is not the most ideal fix out there, but
a real fix would require getting a concurrent variant ZipOutputStream
which I do not believe is worth it.

Fix concurrent writing issues in single file saver

---

build.gradle
src/org/jetbrains/java/decompiler/main/collectors/VarNamesCollector.java
src/org/jetbrains/java/decompiler/main/rels/NestedClassProcessor.java
src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarDefinitionHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarProcessor.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
test/org/jetbrains/java/decompiler/SingleClassesTestBase.java
testData/results/pkg/TestDuplicateLocals.dec
testData/src/java8nodebug/pkg/TestDuplicateLocals.java

In cases where there was no lvt or the lvt was somehow generated (e.g. by a remapper) without considering nested methods quiltflower would sometimes generate variable/parameter names that were already used by an enclosing method.

Fix duplicate local variable names

---

build.gradle
gradle.properties

The Kotlin Gradle plugin has this "feature" where it adds the stdlib as an `implementation` dep automatically. Unfortunately, this is unwanted really often.

Fix Kotlin appearing in the POM

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java
src/org/jetbrains/java/decompiler/main/Fernflower.java
src/org/jetbrains/java/decompiler/main/RecordHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/ConstExprent.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/Exprent.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/FieldExprent.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
src/org/jetbrains/java/decompiler/util/TextBuffer.java
test/org/jetbrains/java/decompiler/BulkDecompilationTest.java
test/org/jetbrains/java/decompiler/SingleClassesTestBase.java

This PR turns the assumptions made by TextBuffer into actual assertions, enabled only in unit test mode for performance reasons. This introduces a fail-fast way to diagnose otherwise obscure bugs quickly and easily.

TextBuffer assertions

---

test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestCastObjectToPrimitive.dec
testData/src/java8/pkg/TestCastObjectToPrimitive.java

While apparently there is a flag to make boxing/unboxing explicit, it isn't the default and this code does not recompile afterwards without it, so I believe that this is worthy of a test

Add test to check for required casts from Object to Boxed primitives

---

src/org/jetbrains/java/decompiler/modules/decompiler/SwitchHelper.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestKotlinEnumWhen.dec
testData/src/kt/pkg/TestKotlinEnumWhen.kt

This still leaves the weird `boolean varXYZ = false;` (or `ICONST_0`) assignments laying around - not sure what the Kotlin compiler is trying to achieve there.
The `findExprents` method is also cursedly general but shouldn't be too much of a perf bottleneck because I avoided streams (the original iteration created streams and `Pair<Statement, Exprent)` even when not needed)

Mostly fix Kotlin enum whens

---

build.gradle

This makes it super easy to know if a given decompiler jar is Quiltflower (as opposed to forge or vanilla fernflower)

Add `Implementation-Name: Quiltflower` to jar manifest

---

src/org/jetbrains/java/decompiler/main/rels/MethodProcessorRunnable.java
src/org/jetbrains/java/decompiler/modules/decompiler/ExitHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/ValidationHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/sforms/FlattenStatementsHelper.java
src/org/jetbrains/java/decompiler/util/DotExporter.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestClassLoop.dec
testData/results/pkg/TestLoopFinally.dec
testData/src/java8/pkg/TestClassLoop.java
testData/src/java8/pkg/TestLoopFinally.java

Fixes cases with inaccessible direct graph nodes for validation, and fix a case where finally statements' successor edges were not put in the direct graph, causing certain methods to fail to decompile.

Fix inacessible digraph nodes

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java
src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
src/org/jetbrains/java/decompiler/struct/attr/StructGeneralAttribute.java
src/org/jetbrains/java/decompiler/struct/attr/StructSourceFileAttribute.java

Unless stripped, the SourceFile attribute contains some pretty valuable information.
Implementation example:
```java
// $FF: compiled from test.java
class Main {
public static void main(String[] var0) {
System.out.println("abc");
}
// $FF: compiled from test.java
private class InternalClass {
}
}
```

feat: SourceFile debug comments

---

build.gradle
testData/results/pkg/TestIllegalVarName.dec
testData/results/pkg/TestKotlinConstructorKt.dec
testData/results/pkg/TestKotlinEnumWhen.dec
testData/results/pkg/TestNamedSuspendFun2Kt.dec
testData/results/pkg/TestRunSuspend.dec
testData/results/pkg/TestSuspendLambdaKt.dec
testData/results/pkg/TestSynchronizedUnprotected.dec

This resolves issues with the kotlin compiler daemon on J17 (which should speed up builds a little bit)
As a bonus, the generated bytecode seems to be a fair bit cleaner now

build: Bump Kotlin version to 1.6.21

---

src/org/jetbrains/java/decompiler/modules/decompiler/SwitchHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/SwitchExprent.java
test/org/jetbrains/java/decompiler/DecompilerTestFixture.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestInlineSwitchExpression1.dec
testData/results/pkg/TestInlineSwitchExpression3.dec
testData/results/pkg/TestSwitchPatternMatching6.dec
testData/results/pkg/TestSwitchPatternMatching7.dec
testData/results/pkg/TestSwitchPatternMatching8.dec
testData/results/pkg/TestSwitchPatternMatching9.dec
testData/src/java17preview/ext/Direction.java
testData/src/java17preview/pkg/TestSwitchPatternMatching6.java
testData/src/java17preview/pkg/TestSwitchPatternMatching7.java
testData/src/java17preview/pkg/TestSwitchPatternMatching8.java
testData/src/java17preview/pkg/TestSwitchPatternMatching9.java

Removes implicit `default -> throw ICCE` branches in exhaustive switch expressions, fixing #111.
Fixes nullable string-switches.
(Also fixes bulk decompilation tests to work on my PC.)
Also introduces test cases for a switch branch with a `default` *and* other options, and nullable switch expressions.

(Exhaustive) switch improvements

---

src/org/jetbrains/java/decompiler/modules/decompiler/SwitchHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/SwitchPatternMatchProcessor.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/SwitchExprent.java
src/org/jetbrains/java/decompiler/modules/decompiler/stats/SwitchStatement.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestSwitchPatternMatching1.dec
testData/results/pkg/TestSwitchPatternMatching10.dec
testData/results/pkg/TestSwitchPatternMatching11.dec
testData/results/pkg/TestSwitchPatternMatching12.dec
testData/results/pkg/TestSwitchPatternMatching3.dec
testData/results/pkg/TestSwitchPatternMatching4.dec
testData/results/pkg/TestSwitchPatternMatching6.dec
testData/results/pkg/TestSwitchPatternMatching7.dec
testData/results/pkg/TestSwitchPatternMatchingConstructor2.dec
testData/results/pkg/TestSwitchPatternMatchingReturn1.dec
testData/src/java17preview/pkg/TestSwitchPatternMatching10.java
testData/src/java17preview/pkg/TestSwitchPatternMatching11.java
testData/src/java17preview/pkg/TestSwitchPatternMatching12.java

Fixes
- Switch statements with `null` labels being decompiled as type labels
- Switch expressions with `null` values being decompiled as the name of the expression type
- Nullable enum switch resugaring
- Type switches with only one code block not being resugared
- Type switches leaving behind an unused synthetic variable

Switch fixes

---

src/org/jetbrains/java/decompiler/main/rels/MethodProcessorRunnable.java
src/org/jetbrains/java/decompiler/modules/decompiler/stats/RootStatement.java

Probably doesn't impact performance greatly, but may reduce iteration allocations for `new ArrayList<>(st.getStats())`.

Don't run processing steps on statements the method doesn't have

---

src/org/jetbrains/java/decompiler/main/rels/ClassWrapper.java
src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectEdge.java
src/org/jetbrains/java/decompiler/modules/decompiler/flow/DirectNodeType.java
src/org/jetbrains/java/decompiler/modules/decompiler/flow/FlattenStatementsHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/stats/Statement.java
src/org/jetbrains/java/decompiler/modules/decompiler/stats/SwitchStatement.java

This PR adds support for representing switch cases in FlattenStatementsHelper by intercepting edges leaving the switch head and adding a case node inbetween. Every test with a switch passes direct graph validation with these changes, meaning that no nodes have been isolated.

Add FlattenStatementsHelper support for switch cases

---

src/org/jetbrains/java/decompiler/modules/decompiler/ExprProcessor.java

This fixes an OOM that we have been seeing, where calling this from within FinallyProcessor could lead to many new objects being created, overloading the garbage collector. I'm not 100% confident that this is the right fix, so I'll test a bit more on my own.

Don't process direct nodes when we've seen them already from another node in ExprProcessor

---

test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestDuplicateAssignmentInSwitchExpr.dec
testData/src/java17/pkg/TestDuplicateAssignmentInSwitchExpr.java

The output fails to compile due to a redeclaration of a variable

Test duplicate assignment in switch expression

---

build.gradle

1) To make the version number available from inside running application. (useful for an about dialog in a GUI displaying the version number)
2) If the jar was renamed for whatever reason, the version can still be found in the manifest,

Added Implementation-Version to manifest

---

src/org/jetbrains/java/decompiler/struct/DirectoryContextSource.java

old:
```
INFO:  Loading Class: /FuzzedClass_21
```
new:
```
INFO:  Loading Class: FuzzedClass_21
```
This only impacts items sourced from directories, not jars.

fix: Correct improper class paths from dir source

---

src/org/jetbrains/java/decompiler/main/Fernflower.java
src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java
src/org/jetbrains/java/decompiler/struct/StructContext.java

Fixes #201, by placing the loaded classes under the right key if it doesn't match their qualified name

Properly resolve source classes in wrong packages

---

src/org/jetbrains/java/decompiler/struct/JarContextSource.java
src/org/jetbrains/java/decompiler/struct/StructContext.java

This handles for example self-executing JARs packaged as EXE file,
which contain the JAR content at the end after the native code.
These files are treated like JAR files, meaning any MANIFEST.MF will
not be extracted.

Detect JAR/ZIP files with other file endings

---

src/org/jetbrains/java/decompiler/struct/StructContext.java

(this is untested in the CLI because I didn't have anything handy, but doesn't cause any test failures)
This isn't really an entire fix for improperly placed *library* classes, but it will move the classes that will actually be decompiled.

fix(struct): Correctly re-enter badly placed classes into the context map

---

src/org/jetbrains/java/decompiler/main/Fernflower.java
src/org/jetbrains/java/decompiler/main/decompiler/ConsoleDecompiler.java
src/org/jetbrains/java/decompiler/main/decompiler/ConsoleHelp.java
src/org/jetbrains/java/decompiler/main/decompiler/OptionParser.java
src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java

This also may allow for easier work on combination flags, like perhaps a `--no-removal` which would apply `--no-remove-bridge --no-remove-synthetic --no-remove-getclass --no-remove-empty-try-catch --no-remove-imports` or something like that

Add long option names & update help message

---

src/org/jetbrains/java/decompiler/util/TextBuffer.java
testData/results/pkg/TestTextTokens2.dec
testData/src/java16/pkg/TestTextTokens2.java

this fix is needed for enigma, since I want to make Quiltflower the default decompiler and this was the last issue to track down first. I also considered moving line 196 out of its else block as a fix, but that seems like it would just be a slower way to accomplish the same thing from a quick look.
fixes https://github.com/QuiltMC/enigma/issues/47, which was causing some generics to explode and look like this:
all credit for tracking this down goes to my brilliant friend @orifu :)

fix improper offset with generics

---

build.gradle

I've tested this with publishToMavenLocal, and it still appears to be producing the same javadoc and sources jars, and it's creating jars with 1980 timestamps.

Ensure deterministic artifact JARs

---

.github/workflows/release.yml
.github/workflows/snapshot.yml
build.gradle

This updates publishing configuration to publish both releases and snapshots only to Central. Pending configuration of secrets for OSSRH auth and GPG keys.

fix: prepare for publishing exclusively to Central

---

src/org/jetbrains/java/decompiler/main/rels/NestedClassProcessor.java

Fixes cases in lambdas where the debug local variable name is used instead of the jad styled local variable name along with in certain cases the type of the local variable not being correct.

Fix local variable jad name and type where the debug name conflicts

---

build.gradle
settings.gradle

(such as apple silicon)
The JVMs that are built for aarch64 are a bit more limited -- I've added the new gradle-recommended toolchain resolver which can find more JVMs, and introduced some logic to pick a 'next best' JVM for compiling test data when running on an ARM system. This allows a full build to run without issue hopefully!

Support building on ARM64

---

test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestLambdaParamTypes.dec
testData/src/java8/pkg/TestLambdaParamTypes.java

VF currently fails to retain type information for the params here, leading to either
1. different behaviour since the lambda now accepts a wider range of inputs, silently eliminating ClassCastExceptions, or
2. code that doesn't compile since it tries to use the more specific parameter type, but fails.
The added test code has both cases.

Add test for lambda param type loss

---

src/org/jetbrains/java/decompiler/modules/decompiler/MergeHelper.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestWhileLambda.dec
testData/src/java8/pkg/TestWhileLambda.java

Fixes a compile error in `RealmsSelectWorldTemplateScreen` where a variable is used in a lambda but the definition is being moved outside a for loop causing the variable to no longer be effectively final.

Fix final variable definition that is used in a for loop being moved outside the for loop

---

src/org/jetbrains/java/decompiler/util/collections/NullableConcurrentHashMap.java
testData/results/pkg/TestGenericsInvocUnchecked.dec

`super.containsKey` calls `this.get(key)` and returns true if the value is not null which means if the key is in the map and the value is null then `containsKey` returns false.

Make containsKey return true if the key is present and the value is null in NullableConcurrentHashMap

---

src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
src/org/jetbrains/java/decompiler/struct/gen/generics/GenericType.java

Fixes some cases where generics were kept even though they aren't available.

Fix keeping generics that are unavailable in the current context

---

src/org/jetbrains/java/decompiler/code/BytecodeVersion.java
src/org/jetbrains/java/decompiler/modules/decompiler/SwitchPatternMatchProcessor.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/SwitchExprent.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestSwitchOnEnumJ21.dec
testData/src/java21/ext/TestEnum2.java
testData/src/java21/pkg/TestSwitchOnEnumJ21.java

For enums in other classes a switch map is used and for switches with a null case pattern matching is used (which has also been released).

Fix switches on enums with a switch map along with null cases for java 21

---

src/org/jetbrains/java/decompiler/modules/decompiler/SwitchExpressionHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/TryWithResourcesProcessor.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestReturnSwitchExpression5.dec
testData/results/pkg/TestSwitchOnEnumJ21.dec
testData/src/java16/pkg/TestReturnSwitchExpression5.java
testData/src/java21/pkg/TestSwitchOnEnumJ21.java

Fixes switch expressions not being converted from a switch statement when a case contains an if statement due to implicit edges created by the if statement along with switch statements that have a case that throws an exception instead of returning a value.

Fix switch expressions not generating

---

plugins/variable-renaming/src/test/java/org/vineflower/variablerenaming/VariableRenamingTest.java
plugins/variable-renaming/testData/results/pkg/TestJADLocalClasses.dec
plugins/variable-renaming/testData/src/java8/pkg/TestJADLocalClasses.java
src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarDefinitionHelper.java

Local classes are only added to the method body after parent contexts are added.

Fix variable namer parent not being set for local classes

---

src/org/jetbrains/java/decompiler/main/ClassesProcessor.java

They may be needed later when writing other classes.
This fixes an issue where non-static inner class constructor invocations from foreign classes would inconsistently have the synthetic enclosing this instance removed from the parameter list, depending on the order they were processed in (and consequently having strange interactions with multithreaded writing)

Don't tear down nested class wrappers after writing the root class

---

src/org/jetbrains/java/decompiler/main/ClassesProcessor.java
src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java

Sometimes it's unnecessary to decompile certain classes, for example libraries such as Apache Commons. Skipping the decompilation of these classes can speed up the overall decompilation time. Currently there is `--only` option, but it doesn't cover cases where we don't know which classes in the JAR to decompile.
This PR adds that option to the decompiler (currently it's `--excluded-class-regex` or `-exc` for shorthand). It will skip the decompilation if the specified regex matches the fully qualified name of the class.
Examples:
```sh
java -jar vineflower.jar '-exc=org/apache/.*' input.jar out_dir
java -jar vineflower.jar '-exc=org/(apache|bouncycastle)/.*|com/google/android/.*' input.jar out_dir
```

Add option to exclude classes from decompilation with regex

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java
testData/results/pkg/TestAnonymousClassConstructor.dec
testData/results/pkg/TestAnonymousClassNaming.dec
testData/results/pkg/TestAnonymousParamNames.dec
testData/results/pkg/TestDoubleNestedClass.dec

This is typically how people actually write code like this (as can be seen in the existing tests).
The improvement is extra noticeable with things like type tokens.
I can add an option for this if wanted. It would also not be hard to expand this to other types of classes, but that seemed less suitable, at least as a default behavior.

Simplify empty anonymous class bodies to `{}`

---

src/org/jetbrains/java/decompiler/modules/decompiler/exps/SwitchExprent.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestSwitchSimpleMultiLine.dec
testData/src/java21/pkg/TestSwitchSimpleMultiLine.java

The test case would previously decompile to
```
public class TestSwitchSimpleMultiLine {
public static <T> Predicate<T> predicates() {
int i = new Random().nextInt();// 8
return switch (i) {// 9
case 0 -> object -> true;// 10
case 1 -> object -> false;// 11
default -> object -> {
boolean r1 = new Random().nextBoolean();// 13
boolean r2 = new Random().nextBoolean();// 14
return r1 && r2 ? true : new Random().nextBoolean();// 15 16 18
};
};
}
}
```

Fix indent on 'simple' switch branches

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestInnerClasses4J21.dec
testData/src/java21/pkg/TestInnerClasses4J21.java

Fixes a case where it would always use the stack size of the first real parameter for synthetic parameters if the method has a signature

Fix stack size of first non synthetic parameter being used for synthetic parameters

---

src/org/jetbrains/java/decompiler/main/rels/MethodProcessor.java
src/org/jetbrains/java/decompiler/modules/decompiler/IntersectionCastProcessor.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/FunctionExprent.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/VarExprent.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestCastIntersectionJ21.dec
testData/results/pkg/TestKotlinConstructorKt.dec
testData/src/java21/pkg/TestCastIntersectionJ21.java

Adds support for intersection types in casts when used for a method or variable.

Add support for intersection types in casts

---

src/org/jetbrains/java/decompiler/main/ClassesProcessor.java
src/org/jetbrains/java/decompiler/main/extern/IFernflowerPreferences.java

Added option to disable inner classes names validation. Useful when the jar that you are decompiling does not follow inner classes naming convention (i.e. does not have `$` in inner class names).

Add option to disable inner classes names validation

---

src/org/jetbrains/java/decompiler/main/rels/NestedClassProcessor.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestRecordLocal.dec
testData/src/java16/pkg/TestRecordLocal.java

Fixes #413 
https://docs.oracle.com/javase/specs/jls/se16/html/jls-8.html#jls-8.10
> A nested record class is implicitly static.

Fix local record classes that have the parent class as the first parameter

---

src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarDefinitionHelper.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestAnonymousClassToLambda.dec
testData/src/java8/pkg/TestAnonymousClassToLambda.java

Fixes cases where a lambda in an anonymous class that is in a method references a parameter from the root method.

Fix lambdas in anonymous classes referencing parameters from the root method

---

test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestLabeledBlockInConstructor.dec
testData/src/java8/pkg/TestLabeledBlockInConstructor.java

This incorrectly decompiles to a `super()` call inside of the labelled block, add a test so it can be fixed later

Add test for labeled blocks in constructor

---

src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestBoxingSuperclass.dec
testData/src/java8/pkg/TestBoxingSuperclass.java

This resolves issues when unboxing seems to not occur on method invocations that occur on superclass methods.
This most notably improves readability of certain codecs / block state definitions.
```diff
public static final Codec<DisplayInfo> CODEC = RecordCodecBuilder.create(
instance -> instance.group(
ItemStack.STRICT_CODEC.fieldOf("icon").forGetter(DisplayInfo::getIcon),
ComponentSerialization.CODEC.fieldOf("title").forGetter(DisplayInfo::getTitle),
ComponentSerialization.CODEC.fieldOf("description").forGetter(DisplayInfo::getDescription),
ResourceLocation.CODEC.optionalFieldOf("background").forGetter(DisplayInfo::getBackground),
AdvancementType.CODEC.optionalFieldOf("frame", AdvancementType.TASK).forGetter(DisplayInfo::getType),
-                Codec.BOOL.optionalFieldOf("show_toast", …
```

Properly walk the inheritance tree when checking for possibly ambiguous unboxed calls

---

src/org/jetbrains/java/decompiler/modules/decompiler/IfPatternMatchProcessor.java
testData/results/pkg/TestPatternMatching17.dec
testData/src/java17/pkg/TestPatternMatching17.java

Fixes pattern matching instanceof not always being detected inside loops due to the predecessors check ending up inside the statement

Fix pattern matching instanceof not being detected inside loops

---

test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestLVTReassignment.dec
testData/src/java8/pkg/TestLVTReassignment.java

This includes a test for a strange issue that causes LVT reassignments to be lost. 
```java
double one = 1;
double shouldBeOne = one;
one = 0;
if (one > 1) {
}
System.out.println(shouldBeOne); // -> 1.0
```
```java
double one = 1.0;
one = 0.0;
if (one > 1.0) {
}
System.out.println(one); // -> 0.0
```
It should be noted that without the if statement, it appears to work fine.
```
// Decompiles to without if statement
double one = 1.0;
double var5 = 0.0; // <- although interestingly, this LVT name is lost
System.out.println(one);
```

Add test for Expression Optimization Issue

---

src/org/jetbrains/java/decompiler/struct/StructClass.java

Requesting the record components from a struct class has a fallback to
an empty list over null for objects that extend j.l.Record but do not
have a record attribute.
This fallback however assumes that the type has a superclass, which is
not the case for j.l.Object, causing a NPE.

Prevent NPE on #getRecordComponents for Object

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java
src/org/jetbrains/java/decompiler/main/RecordHelper.java
src/org/jetbrains/java/decompiler/main/rels/MethodWrapper.java
src/org/jetbrains/java/decompiler/struct/StructClass.java
testData/results/pkg/TestRecordEmptyConstructor.dec
testData/results/pkg/TestRecordGenericVararg.dec

[Minecraft diff](https://pastes.dev/KclRDfN7iR)
Would love feedback on the method pruning, not sure if there is a prefered way I should be doing this.
Additionally, I have to store a flag that a method wrapper is a compact constructor as I prune the fields making the check no longer valid later in the code.

 Compact canonical constructor support
