test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestPrivateClasses.dec
testData/src/java8/pkg/TestPrivateClasses.java

Restore PrivateClasses test

---

src/org/jetbrains/java/decompiler/main/decompiler/ConsoleDecompiler.java
src/org/jetbrains/java/decompiler/struct/ContextUnit.java
src/org/jetbrains/java/decompiler/struct/StructContext.java

Given that the affected lines were last changed with https://github.com/QuiltMC/quiltflower/pull/18 and that that PR does not have a description, I have no real idea if I interpreted the use of the method correctly

Dont save directory entries as files

---

src/org/jetbrains/java/decompiler/code/CodeConstants.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestMethodHandles.dec
testData/results/pkg/TestVarHandles.dec
testData/src/java8/pkg/TestMethodHandles.java
testData/src/java9/pkg/TestVarHandles.java

This adds missing casts to MethodHandle and VarHandle calls

Add support for signature polymorphic methods

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java
src/org/jetbrains/java/decompiler/main/ClassesProcessor.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestLocalEnum.dec
testData/results/pkg/TestLocalInterface.dec
testData/results/pkg/TestLocalRecord.dec
testData/src/java16/pkg/TestLocalRecord.java

Add local enum and interface support

---

test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestComplexIfElseChain.dec
testData/src/java8/pkg/TestComplexIfElseChain.java

Hopefully we can fix this at some point

Add test for ugly if-else chain

---

src/org/jetbrains/java/decompiler/modules/decompiler/IfHelper.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestComplexIfElseChain.dec
testData/src/java8/pkg/TestComplexIfElseChain.java

Appears to improve readability of if/else chains around the place

Fix complex if-else chain

---

test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestOldECJInner.dec
testData/src/jasm/TestOldECJInner$Inner.jasm
testData/src/jasm/TestOldECJInner.jasm

Produces code that doesn't compile

Add test for old ECJ Inner

---

test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestSwapException.dec
testData/src/jasm/TestSwapException.jasm

A simple test for the bug fixed by 4dd8d9197374efc3e406ae5b6d521100f6f469fe.

Add test for swapping exception creation

---

build.gradle
src/net/fabricmc/fernflower/api/IFabricResultSaver.java
src/org/jetbrains/java/decompiler/main/decompiler/ConsoleDecompiler.java
src/org/jetbrains/java/decompiler/main/extern/IResultSaver.java
src/org/jetbrains/java/decompiler/struct/ContextUnit.java

This should allow VanillaGradle to use Quiltflower, with only minor changes needed on our side.

Adjust IResultSaver to support both Fabricflower and Forgeflower APIs

---

src/org/jetbrains/java/decompiler/modules/decompiler/IdeaNotNullHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/StatEdge.java
src/org/jetbrains/java/decompiler/modules/decompiler/stats/Statement.java

A few cool StatEdge methods to manage stuff *easier*.

Provide new api to handle StatEdges

---

src/org/jetbrains/java/decompiler/modules/decompiler/EliminateLoopsHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/IfHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/LabelHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/MergeHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/StatEdge.java
src/org/jetbrains/java/decompiler/modules/decompiler/SwitchExpressionHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/ValidationHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/stats/Statement.java

Fixes most issues with statement graph validation, regarding edges and graph structures. Directgraph validation fixes will be in another PR. The ternary processor isn't included here because it's being refactored already in another PR.

Fix statement graph validation

---

src/org/jetbrains/java/decompiler/modules/decompiler/IfPatternMatchProcessor.java
testData/results/pkg/TestPatternMatching17FakeNew.dec
testData/results/pkg/TestPatternMatchingFakeNew.dec

Commit [1185b22](https://github.com/QuiltMC/quiltflower/commit/1185b22eaca34aeac753c17e81726a206b0ffd16) shows the improvements in the tests in the current code base.

Do not allow the `IfPatternMatchProcessor` to override an earlier match

---

src/org/jetbrains/java/decompiler/code/CodeConstants.java
src/org/jetbrains/java/decompiler/main/ClassWriter.java
testData/results/module-info.dec
testData/src/java9/sample.module/module-info.java

Add support for static and transitive modifiers of 'requires' in module-info

---

test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestArrayConstructorReference.dec
testData/results/pkg/TestArrayConstructorReferenceJrt.dec
testData/src/java8/pkg/TestArrayConstructorReference.java
testData/src/java8/pkg/TestArrayConstructorReferenceJrt.java

See discord discussions. I think it would be good to resugar it to `int[]::new` instead of a lambda.

Add test for array constructor references

---

src/org/jetbrains/java/decompiler/struct/SingleFileContextSource.java
src/org/jetbrains/java/decompiler/struct/StructContext.java

Fixes #205, which wasn't the actual problem, but still is related

Allow using "fake" files as source

---

testData/results/pkg/TestCastObjectToPrimitive.dec
testData/src/java8/pkg/TestCastObjectToPrimitive.java

The issue might also exist for other structures

Add further tests to check for required casts from Object to Boxed primitives

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java
src/org/jetbrains/java/decompiler/main/ClassesProcessor.java
src/org/jetbrains/java/decompiler/main/DecompilerContext.java
src/org/jetbrains/java/decompiler/main/Fernflower.java
src/org/jetbrains/java/decompiler/main/decompiler/PrintStreamLogger.java
src/org/jetbrains/java/decompiler/main/extern/IFernflowerLogger.java
src/org/jetbrains/java/decompiler/struct/ContextUnit.java
src/org/jetbrains/java/decompiler/struct/IDecompiledData.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestInnerClassExtend.dec
testData/results/pkg/TestInnerClassReference.dec
testData/src/java8/ext/SomeOuterClass.java
testData/src/java8/pkg/TestInnerClassExtend.java
testData/src/java8/pkg/TestInnerClassReference.java

wip, needs to re-incorporate VF error handling to emit the appropriate info

fix: pull in processing decompile phase from Forgeflower threading impl

---

README.md
build.gradle
src/org/jetbrains/java/decompiler/main/ClassWriter.java
src/org/jetbrains/java/decompiler/main/ClassesProcessor.java
src/org/jetbrains/java/decompiler/main/DecompilerContext.java
src/org/jetbrains/java/decompiler/main/Fernflower.java
src/org/jetbrains/java/decompiler/main/decompiler/PrintStreamLogger.java
src/org/jetbrains/java/decompiler/main/extern/IFernflowerLogger.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/ConstExprent.java
src/org/jetbrains/java/decompiler/struct/ContextUnit.java
src/org/jetbrains/java/decompiler/struct/IDecompiledData.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestInnerClassExtend.dec
testData/results/pkg/TestInnerClassReference.dec
testData/src/java8/ext/SomeOuterClass.java
testData/src/java8/pkg/TestInnerClassExtend.java
testData/src/java8/pkg/TestInnerClassReference.java

Changelog:
```
* Fixed inconsistent decompilation with floating point values
* Fixed inconsistent decompilation with non-static inner classes
```

Release 1.9.3

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java
testData/results/pkg/TestArrayConstructorReference.dec
testData/results/pkg/TestArrayConstructorReferenceJrt.dec
testData/results/pkg/TestDoubleForeach.dec

Adds support for array constructor references

Add support for array constructor references

---

src/org/jetbrains/java/decompiler/main/rels/NestedClassProcessor.java
testData/results/pkg/TestLocalRecord.dec
testData/src/java16/pkg/TestLocalRecord.java

I am not sure if this is good enough, but it fixes the test and doesn't cause a change in any other test, so it should be a good first step

Consider lambdas when searching where to place local class definitions (fixes #314)

---

src/org/jetbrains/java/decompiler/modules/decompiler/IfPatternMatchProcessor.java
testData/results/pkg/TestSwitchPatternMatchingInstanceof4.dec

Adds support for generics in the type part of pattern matching instanceof.

Allow using generics with pattern matching instanceof

---

plugins/kotlin/src/main/java/org/vineflower/kotlin/expr/KFunctionExprent.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KType.java
src/org/jetbrains/java/decompiler/code/interpreter/InstructionImpact.java
src/org/jetbrains/java/decompiler/main/ClassWriter.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/ArrayExprent.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/ConstExprent.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/FunctionExprent.java
src/org/jetbrains/java/decompiler/modules/decompiler/vars/VarDefinitionHelper.java
src/org/jetbrains/java/decompiler/struct/gen/VarType.java
src/org/jetbrains/java/decompiler/struct/gen/generics/GenericType.java
testData/results/pkg/TestForCyclicVarDef.dec
testData/results/pkg/TestIfElseTernary1.dec
testData/results/pkg/TestIfElseTernary1J17.dec
testData/results/pkg/TestInfiniteLoop.dec
testData/results/pkg/TestNestedTernaryCondition.dec
testData/results/pkg/TestTryReturn.dec

Fully remove fakeBooleans and useless copy

Remove unneeded source of fake booleans

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java

Fix @Override annotations emitting twice

---

src/org/jetbrains/java/decompiler/main/ClassWriter.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestLambdaToAnonymousClass.dec
testData/results/pkg/TestLambdaToAnonymousClass2.dec
testData/src/java8/pkg/TestLambdaToAnonymousClass.java
testData/src/java8/pkg/TestLambdaToAnonymousClass2.java

introduced in https://github.com/Vineflower/vineflower/commit/4b78dd4135895873b87f5e52702e80769b9842a1 (#312)
fixes #333

fix lambda to anonymous class regression

---

src/org/jetbrains/java/decompiler/modules/decompiler/ValidationHelper.java
src/org/jetbrains/java/decompiler/modules/decompiler/exps/NewExprent.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestSwitchInTry.dec
testData/src/java8/pkg/TestSwitchInTry.java

Fix copying of array exprents and add validation checks for duplicated exprents

---

src/org/jetbrains/java/decompiler/modules/decompiler/exps/InvocationExprent.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestBlankLinesSpaces.dec
testData/src/java8/pkg/TestBlankLinesSpaces.java

Fix formatter emitting blank lines for long method invocations with no arguments

---

src/org/jetbrains/java/decompiler/main/rels/NestedClassProcessor.java
test/org/jetbrains/java/decompiler/SingleClassesTest.java
testData/results/pkg/TestInnerClasses3J21.dec
testData/src/java21/pkg/TestInnerClasses3J21.java

Adds an `assigned` field to `VarFieldPair` so that when checking the fields they are only compared if they are known to be correct.

Fix 2 constructors of a non-static inner class with 1 calling another

---

plugins/kotlin/src/main/java/org/vineflower/kotlin/KotlinWriter.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/expr/KAnnotationExprent.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/expr/KFunctionExprent.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/metadata/MetadataNameResolver.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/pass/EliminateDeadVarsPass.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/pass/KMergePass.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/pass/ReplaceExprentsPass.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/DefaultArgsMap.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KConstructor.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KContract.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KFunction.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KParameter.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KProperty.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KPropertyAccessor.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KType.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/struct/KTypeParameter.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/util/KTypes.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/util/KUtils.java
plugins/kotlin/src/main/java/org/vineflower/kotlin/util/ProtobufFlags.java

Also fixes a couple issues involving constructor parameter defaults, including a full decompilation error.

Update Kotlin plugin to use modern Java features
